### PR TITLE
Made more strict regex matches for some annoying responses. Added some fun new responses

### PR DESCRIPTION
**Pull request by Hobbyte**

### CODE REVIEW

**Comment by DjofPlusPlus** [comment]
👍

**Comment by Psyrixx** [comment]
edit status revoked




jk

--
*Robert Sogomonian* | *Owner*
Psyjnir, Inc

5067 Clayton Road | Concord, CA 94521
website <http://www.psyjnir.com/> | email <rsogomonian@psyjnir.com> |
*mobile*: (925) 766-0869

**Comment by jwheare** [comment]
Emojis look fucked

**Comment by jwheare** [comment]
gh 🇬🇭

**Pull request merged**
